//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo_Raf_Urun
    {
        public int raf_urun_id { get; set; }
        public Nullable<int> urun1_id { get; set; }
        public Nullable<int> urun2_id { get; set; }
        public string urun1_isim { get; set; }
        public string urun2_isim { get; set; }
        public int raf_id { get; set; }
        public int urun_sayac { get; set; }
        public int i { get; set; }
        public int j { get; set; }
        public string urun1_kodu { get; set; }
        public string irsaliye_no { get; set; }
        public Nullable<System.DateTime> irsaliye_tarihi { get; set; }
        public Nullable<double> miktar { get; set; }
        public string RFIDtag { get; set; }
        public string Barkod { get; set; }
        public string lot_no { get; set; }
        public Nullable<int> is_emri_id { get; set; }
    }
}
