//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo_Alan
    {
        public int depo_id { get; set; }
        public string alan_kodu { get; set; }
        public string alan_adi { get; set; }
        public double konum_sol { get; set; }
        public double konum_ust { get; set; }
        public double genislik { get; set; }
        public double yukseklik { get; set; }
        public string alan_renk { get; set; }
        public int alan_id { get; set; }
        public string RFIDtag { get; set; }
        public string Barkod { get; set; }
    }
}
