//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo_Raf
    {
        public int depo_id { get; set; }
        public string raf_kodu { get; set; }
        public string raf_adi { get; set; }
        public double konum_sol { get; set; }
        public double konum_ust { get; set; }
        public double genislik { get; set; }
        public double yukseklik { get; set; }
        public int satir_sayisi { get; set; }
        public int sutun_sayisi { get; set; }
        public int raf_id { get; set; }
        public int raf_urun_kapasitesi { get; set; }
    }
}
