//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo
    {
        public int DEPO_ID { get; set; }
        public int UST_DEPO_ID { get; set; }
        public int ALT_DEPO_SAYISI { get; set; }
        public string DEPO_KODU { get; set; }
        public string ADI { get; set; }
        public string ADRES { get; set; }
        public Nullable<int> ADRES_SEHIR { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string FAX1 { get; set; }
        public string FAX2 { get; set; }
        public string POSTA_KODU { get; set; }
        public string ACIKLAMA1 { get; set; }
        public string ACIKLAMA2 { get; set; }
        public Nullable<int> OLUSTURAN { get; set; }
        public Nullable<System.DateTime> OLUS_TAR { get; set; }
        public Nullable<int> DEGISTIREN { get; set; }
        public Nullable<System.DateTime> DEGIS_TAR { get; set; }
    }
}
