//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo_Alan_Urun
    {
        public int alan_urun { get; set; }
        public Nullable<int> urun_id { get; set; }
        public string urun_kodu { get; set; }
        public string urun_adi { get; set; }
        public string irsaliye_no { get; set; }
        public Nullable<System.DateTime> irsaliye_tarihi { get; set; }
        public Nullable<double> miktar { get; set; }
        public Nullable<int> alan_id { get; set; }
        public string tag { get; set; }
        public string sicil_kod { get; set; }
        public Nullable<int> is_emri_id { get; set; }
        public Nullable<int> makine_id { get; set; }
        public string lot_no { get; set; }
    }
}
