//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_QRCode
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mlz_Depo_Raf_Urun_Detay
    {
        public int raf_detay_id { get; set; }
        public Nullable<int> raf_urun_id { get; set; }
        public Nullable<int> urun_id { get; set; }
        public string urun_kodu { get; set; }
        public string irs_no { get; set; }
        public Nullable<System.DateTime> irs_tarih { get; set; }
        public Nullable<double> miktar { get; set; }
        public string rfid { get; set; }
        public string barkod { get; set; }
        public string lot_no { get; set; }
    }
}
